"""Add relationship between Pizza and Topping

Revision ID: 4354025d5c66
Revises: 41c686d65ff8
Create Date: 2024-11-14 00:20:20.272762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4354025d5c66'
down_revision: Union[str, None] = '41c686d65ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
